FROM node:18

WORKDIR /app

# Copia apenas package.json para fazer cache do npm install
COPY package*.json ./

RUN npm install

# Copia o código (será sobrescrito pelo volume)
COPY . .

EXPOSE 3000

# React Dev Server (react-scripts start)
CMD ["npm", "start"]